### ISSUE TITLE
Nested modules with automatic namespace

### ISSUE THREAD

**Issue by matiaseche** [gap777/automatic_namespaces#7]
Hello! Thanks for developing this gem, it's great!

Currently I am trying to add support for nested modules but I could not make it work, so I come here for help.
I have the following structure:
```
- app
- ...
- ...
- packs/
  - team1/ # This is not a pack
    - first_pack/ # This is a pack
    - second_pack/
    - third_pack/
  - team2/ # This is not a pack
    - fourth_pack/ # This is a pack
    - fifth_pack/
    - ...
```

Up to there no problem. Everything works fine.

Now what I am trying to do is to set the namespaces as `Team1::FirstPack`, this would help me alot to manage the code ownership and to explicitly tell the developers where the code they use should be, which will also help with the process to define dependencies.

I first tried adding the following to the `packs/team1/package.yml`
```yml
...
metadata:
  automatic_pack_namespace: true
  namespace_override: Team1::FirstPack
```

With no success. Then I thought: maybe I can "override" a parent just like is done with the namespace.

```yml
...
metadata:
  automatic_pack_namespace: true
  namespace_override: FirstPack
  namespace_parent: Team1
```

But I could not make it work. Any help on this would be great :)
